CREATE DATABASE HR;
USE HR;
source dotr1jnBEeirWBJEBbG4Hg_774f09a039c111e88d9d77a1dc9cd80f_Script_Create_Tables.sql
CREATE DATABASE SHOP;
USE SHOP;
source r83pLIFkEeiEShL6YrwsWg_b021fbd0816411e8ac666ffdad9733b0_PETSALE-CREATE.sql
select DAY(SALEDATE) from PETSALE where ANIMAL = 'Cat';
select SUM(SALEPRICE) from PETSALE;
select SUM(SALEPRICE) as SUM_OF_SALEPRICE from PETSALE;
select MAX(QUANTITY) from PETSALE;
select AVG(SALEPRICE) from PETSALE;select AVG( SALEPRICE / QUANTITY ) from PETSALE where ANIMAL = 'Dog';
select * from PETSALE where LCASE(ANIMAL) = 'cat';
select COUNT(*) from PETSALE where MONTH(SALEDATE)='05';
SELECT * FROM PETSALE WHERE LENGTH(ANIMAL) > (SELECT AVG(LENGTH(ANIMAL)) FROM PETSALE);
SELECT * FROM PETSALE WHERE ROUND(SALEPRICE) > ((SELECT AVG(SALEPRICE) FROM PETSALE) > (SELECT AVG(SALEPRICE) FROM PETSALE LIMIT 10));  